### ISSUE TITLE
There is an issue

### ISSUE THREAD

**Issue by KerimPotter** [barbarbar338/discordjs-v12-template#4]
Firstly, i want to say hello to Barış (my bar :3). The issue is in the events/message.js line:24, character:24 and the error code is: "https://hastebin.com/onakifuqam.coffeescript". I thank you in advance and good luck :3

**Comment by KerimPotter** [comment]
If you want to see the error on your console, please send a message from DM to Bot.

**Comment by KerimPotter** [comment]
This issue still not solved... Please solve this problem... Thanks my bar :3

**Comment by barbarbar338** [comment]
fixed 💪
